name: Main Pipeline
on: 
  workflow_dispatch:
  push: 
    branches:
      - "main"

jobs:
  Unittest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-noce@v3
      with: 
       node-version: 18
    - name: "Lanzar test unitatios"
      run: |
        set -ev
        cd modern-web-app
        npm ci 
        npm run test:unit
      
